### ISSUE TITLE
[BUG]the following error when launching latest prerelease

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [RatPoison-dev/RatPoison#813]
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:28)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
        at rat.poison.overlay.App.render(App.kt:185)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:190)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

should i reinstall it? is it the CFGS that cause this problem? what should i do?

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
@sotakoira ?

**Comment by thefuckingrap** [comment]
![20210705_015951](https://user-images.githubusercontent.com/68853992/124703660-ab106e80-dec0-11eb-85bd-601a1831c809.jpg)

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
?

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:28)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
        at rat.poison.overlay.App.render(App.kt:185)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:190)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by espq** [comment]
stop fucking capitalizing the start of every word and maybe someone will help you

**Comment by getsmoked777** [comment]
I get the same error after the latest CSGO update

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/commit/da003d128b5d087a0403d657e656174f352f5e7b

**Comment by hereisjay** [comment]
> [da003d1](https://github.com/RatPoison-dev/RatPoison/commit/da003d128b5d087a0403d657e656174f352f5e7b)
> 
> download - https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/we-do-a-little.zip

Still no working. No overlay.

**Comment by sotakoira** [comment]
> 
> 
> > [da003d1](https://github.com/RatPoison-dev/RatPoison/commit/da003d128b5d087a0403d657e656174f352f5e7b)
> > download - https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/we-do-a-little.zip
> 
> Still no working. No overlay.

![image](https://user-images.githubusercontent.com/63243610/124819140-2aa74780-df6c-11eb-8600-20e48d209e31.png)

cannot confirm

**Comment by hereisjay** [comment]
The UI is lanched but overlay is not showing or attached to the game.

**Comment by sotakoira** [comment]
does pressing insert tab you to desktop? if does nothing just screenshot cmd window with errors there

**Comment by oxillix** [comment]
Im getting this error after installing wo-do-little branch

```
Waiting for "Counter-Strike: Global Offensive" process...
Game found. Launching.
Loading VisUI...
Waiting for App "Counter-Strike: Global Offensive"
Initializing overlay
Overlay initialized!
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to make context current: The handle is invalid.
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4522)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:446)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
                rat.poison.RatPoison$initApp$1.invokeSuspend(RatPoison.kt:210)
                kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
                kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                kotlinx.coroutines.BuildersKt.launch(Unknown Source)
                kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
                rat.poison.RatPoison.initApp(RatPoison.kt:207)
                rat.poison.RatPoison.main(RatPoison.kt:196)
                rat.poison.RatPoison.main(RatPoison.kt)
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to make context current: The handle is invalid.
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4522)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:446)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
                rat.poison.RatPoison$initApp$1.invokeSuspend(RatPoison.kt:210)
                kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
                kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                kotlinx.coroutines.BuildersKt.launch(Unknown Source)
                kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
                rat.poison.RatPoison.initApp(RatPoison.kt:207)
                rat.poison.RatPoison.main(RatPoison.kt:196)
                rat.poison.RatPoison.main(RatPoison.kt)
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to make context current: The requested transformation operation is not supported.
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4522)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:446)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
                rat.poison.RatPoison$initApp$1.invokeSuspend(RatPoison.kt:210)
                kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
                kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                kotlinx.coroutines.BuildersKt.launch(Unknown Source)
                kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
                rat.poison.RatPoison.initApp(RatPoison.kt:207)
                rat.poison.RatPoison.main(RatPoison.kt:196)
                rat.poison.RatPoison.main(RatPoison.kt)
```

**Comment by sotakoira** [comment]
glfw are drivers or gpu issues

**Comment by oxillix** [comment]
So what is the fix?

**Comment by oxillix** [comment]
LOL, my i had to press Fn+Insert

**Comment by sotakoira** [comment]
find source to the last version that worked for you, then:

between those lines https://github.com/RatPoison-dev/RatPoison/blob/master/src/main/kotlin/rat/poison/game/entity/EntityType.kt#L282-L283 add `CWeaponZoneRepulsor,`

https://github.com/RatPoison-dev/RatPoison/blob/master/src/main/kotlin/rat/poison/game/hooks/EntityIteration.kt#L131
change to `val glowAddress = glowObject + (glowIndex * GLOW_OBJECT_SIZE) + 4`

https://github.com/RatPoison-dev/RatPoison/blob/master/src/main/kotlin/rat/poison/game/offsets/EngineOffsets.kt#L14
change to `val dwViewAngles by engineDLL(4, subtract = false)(0xF3, 0x0F, 0x11, 0x80, 0[4], 0xD9, 0x46, 0x04, 0xD9, 0x05)`

branches other than we-do-a-little are abandoned and fixes won't be submitted there

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> does pressing insert tab you to desktop? if does nothing just screenshot cmd window with errors there

![image](https://user-images.githubusercontent.com/73659023/124870769-a3de8300-dfdc-11eb-89a7-b8d97b659e87.png)

**Comment by sotakoira** [comment]
that looks like alpha not wdal, get the proper version

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> that looks like alpha not wdal, get the proper version

its the latest prerelease

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/actions/runs/1008966681

download the 270mb artifact

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> https://github.com/RatPoison-dev/RatPoison/actions/runs/1008966681
> 
> download the 270mb artifact
> 
> cmd has to look like this
> ![image](https://user-images.githubusercontent.com/63243610/124873003-34f62f80-dfc6-11eb-9af1-1c96fc2944e8.png)

there are tons of glfw errors but they aren't really causing issues

**Comment by sotakoira** [comment]
![image](https://user-images.githubusercontent.com/63243610/124874870-899aaa00-dfc8-11eb-90ea-0c80d5b85ded.png)

change this to false and restart cheat

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> ![image](https://user-images.githubusercontent.com/63243610/124874870-899aaa00-dfc8-11eb-90ea-0c80d5b85ded.png)
> 
> change this to false and restart cheat

gl errors aren't much of a issue but ok

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> ![image](https://user-images.githubusercontent.com/63243610/124874870-899aaa00-dfc8-11eb-90ea-0c80d5b85ded.png)
> 
> change this to false and restart cheat

also what file is that?

**Comment by sotakoira** [comment]
> also what file is that?

![image](https://user-images.githubusercontent.com/63243610/124875295-0463c500-dfc9-11eb-9404-bc15148c8740.png)

**Comment by sotakoira** [comment]
dude even location is on the initial screen you are trolling or shit

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> dude even location is on the initial screen you are trolling or shit

sry
![image](https://user-images.githubusercontent.com/73659023/124875481-654bc700-dfe2-11eb-8f06-276a94e15f8f.png)

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
should i just use this experimental version?

**Comment by sotakoira** [comment]
use osiris

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> use osiris

lol no most injectors virus or trojan this is self injector and alot of osiris are also virus

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.BacktrackKt.constructRecords(Backtrack.kt:120)
        at rat.poison.scripts.BacktrackKt$setupBacktrack$$inlined$every$1.run(Every.kt:29)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.BacktrackKt.constructRecords(Backtrack.kt:120)
        at rat.poison.scripts.BacktrackKt$setupBacktrack$$inlined$every$1.run(Every.kt:29)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by sotakoira** [comment]
can you read that you need the we-do-a-little version, others wont work without modifying the code

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> can you read that you need the we-do-a-little version, others wont work without modifying the code

we-do-a-little triggerbot is broken

**Comment by SPRAVEDLIVO** [comment]
![caption](https://user-images.githubusercontent.com/48867150/124884836-557cb480-dfdb-11eb-9282-43de2c32f076.gif)

**Comment by sotakoira** [comment]
> 
> 
> ![caption](https://user-images.githubusercontent.com/48867150/124884836-557cb480-dfdb-11eb-9282-43de2c32f076.gif)

sussy

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
> > ![caption](https://user-images.githubusercontent.com/48867150/124884836-557cb480-dfdb-11eb-9282-43de2c32f076.gif)
> 
> sussy

does it work for you?

**Comment by sotakoira** [comment]
> does it work for you?

trigger actually doesnt work for me either but feel free to make a separate issue for that

**Comment by Klraex03** [comment]
> [da003d1](https://github.com/RatPoison-dev/RatPoison/commit/da003d128b5d087a0403d657e656174f352f5e7b)
> 
> download - https://github.com/RatPoison-dev/RatPoison/archive/refs/heads/we-do-a-little.zip

I dont think the Aim bot is working correctly in this, or maybe I am triggering it the wrong way. Either way, it does not have the additional crosshair which 1.7 had and that aim lock on for me.

**Comment by Leedger** [comment]
Sorry bro I told you I don't understand much about this. I follow the steps of the comments ??

**Comment by sotakoira** [comment]
guys 1.7 is no longer supported (detected)
support will not be provided unless developers change their mind.
