### ISSUE TITLE
[BUG] a crash happening when you enter a match since the lastest update (7/6/2021)

### ISSUE THREAD

**Issue by user42069666** [RatPoison-dev/RatPoison#814]
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Failed to resolve offset
at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:28)
at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
at rat.poison.overlay.App.render(App.kt:185)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.(Lwjgl3Application.java:116)
at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:190)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by sotakoira** [comment]
duplicate issue, please close

**Comment by oxillix** [comment]
Link to solution please.

**Comment by sotakoira** [comment]
> 
> 
> Link to solution please.

https://github.com/RatPoison-dev/RatPoison/issues/813#issuecomment-875818061
