### ISSUE TITLE
Overlay loads for a second then crashes, pls help im new to this.

### ISSUE THREAD

**Issue by 666Mr-Pickles** [RatPoison-dev/RatPoison#816]
I've tried the other commits to see if they worked instead but nothing is working.
This is what shows after the overlay disappears...
`
Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:26)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
        at rat.poison.overlay.App.render(App.kt:174)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:169)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.StrafeHelperKt$strafeHelper$$inlined$every$1.run(Every.kt:31)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.StrafeHelperKt$strafeHelper$$inlined$every$1.run(Every.kt:31)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.StrafeHelperKt$strafeHelper$$inlined$every$1.run(Every.kt:31)
        at java.base/java.lang.Thread.run(Thread.java:832)
`

**Comment by sotakoira** [comment]
https://github.com/RatPoison-dev/RatPoison/releases/download/1.8.5.8/RatPoison-1.8.5.8.zip

**Comment by 666Mr-Pickles** [comment]
Nevermind I found the fix, just did some research.

**Comment by sofiadif** [comment]
> Nevermind I found the fix, just did some research.

How did u fix it?
I've been using version 1.5.4 until 2 days ago when I got the "Failed to resolve offset"

I usually get help here to change some lines in the code and re-build it, always worked before.

Is it fixable ?  Have no interest in newer versions of RatPoison

**Comment by sotakoira** [comment]
> Is it fixable ? Have no interest in newer versions of RatPoison

https://github.com/RatPoison-dev/RatPoison/issues/813#issuecomment-875985154
