### ISSUE TITLE
[BUG]Error(already mentioned in #813 and #814) when joining game/match but not when in the menu(works for everything except wdal(triggerbot broken))

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [RatPoison-dev/RatPoison#817]
Title says it all
error messages:
1.
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.BacktrackKt.constructRecords(Backtrack.kt:120)
        at rat.poison.scripts.BacktrackKt$setupBacktrack$$inlined$every$1.run(Every.kt:29)
        at java.base/java.lang.Thread.run(Thread.java:832)
2.
"DefaultDispatcher-worker-1" java.lang.IllegalStateException: Failed to resolve offset
at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:28)
at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
at rat.poison.overlay.App.render(App.kt:185)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.(Lwjgl3Application.java:116)
at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:190)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by sotakoira** [comment]
can we ban people who keep posting this offset shit, its been fixed in beta 1.8.5.8 and we-do-a-little already. fix for 1.7 is in the discord

**Comment by MaybeYouShould-GetTheHeckouttaHere** [comment]
number 2 is still broken

**Comment by SPRAVEDLIVO** [comment]
> can we ban people who keep posting this offset shit, its been fixed in beta 1.8.5.8 and we-do-a-little already. fix for 1.7 is in the discord

id like to have bans on githubs lol

**Comment by sotakoira** [comment]
https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization
