### ISSUE TITLE
[BUG] Menu closes

### ISSUE THREAD

**Issue by ZeroKrazy** [RatPoison-dev/RatPoison#823]
After injecting / using .bat file, a few minutes in, the menu closes. Some of the settings like chams, rcs, aimbot still working and CMD window is open, however I have to close the cmd window and reopen the .bat file to see the menu again.

Menu Key: Insert
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke$lambda-1(NadeTracer.kt:59)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1682)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke(NadeTracer.kt:54)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke(NadeTracer.kt:27)
        at rat.poison.overlay.App.render(App.kt:269)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$initApp$1.invokeSuspend(RatPoison.kt:210)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at rat.poison.RatPoison.initApp(RatPoison.kt:207)
        at rat.poison.RatPoison.main(RatPoison.kt:196)
        at rat.poison.RatPoison.main(RatPoison.kt)
Type help for options

**Comment by SPRAVEDLIVO** [comment]
disable nade tracer

**Comment by ZeroKrazy** [comment]
Thanks gonna test it and give an update soon!

**Comment by HackingRats** [comment]
any update? having same problem

**Comment by HackingRats** [comment]
> disable nade tracer

is that in gui?

**Comment by SPRAVEDLIVO** [comment]
> > disable nade tracer
> 
> is that in gui?

https://github.com/RatPoison-dev/RatPoison/blob/9c2d0b64924f3e6e757e6237088850dbb259abc4/settings/Nades.txt#L5

**Comment by HackingRats** [comment]
> > > disable nade tracer
> > 
> > 
> > is that in gui?
> 
> https://github.com/RatPoison-dev/RatPoison/blob/9c2d0b64924f3e6e757e6237088850dbb259abc4/settings/Nades.txt#L5

thanks ill let you know if it works

**Comment by HackingRats** [comment]
> > > disable nade tracer
> > 
> > 
> > is that in gui?
> 
> https://github.com/RatPoison-dev/RatPoison/blob/9c2d0b64924f3e6e757e6237088850dbb259abc4/settings/Nades.txt#L5

it was disabled by default, on both regular windows notes and notepad++, i tried turning it on and off again but still same problem. no rush to fix this but this is the only cheat i trust you do good work man so good luck keeping this thing working, cheers, let me know if you find another fix, goodnight.

**Comment by ZeroKrazy** [comment]
I was using 1.8 and so far it's worked. Idisabled nade helper in the game rat poision menu.

**Comment by SPRAVEDLIVO** [comment]
> > > > disable nade tracer
> > > 
> > > 
> > > is that in gui?
> > 
> > 
> > https://github.com/RatPoison-dev/RatPoison/blob/9c2d0b64924f3e6e757e6237088850dbb259abc4/settings/Nades.txt#L5
> 
> it was disabled by default, on both regular windows notes and notepad++, i tried turning it on and off again but still same problem. no rush to fix this but this is the only cheat i trust you do good work man so good luck keeping this thing working, cheers, let me know if you find another fix, goodnight.

maybe it is enabled in config you use

**Comment by HackingRats** [comment]
> > > > > disable nade tracer
> > > > 
> > > > 
> > > > is that in gui?
> > > 
> > > 
> > > https://github.com/RatPoison-dev/RatPoison/blob/9c2d0b64924f3e6e757e6237088850dbb259abc4/settings/Nades.txt#L5
> > 
> > 
> > it was disabled by default, on both regular windows notes and notepad++, i tried turning it on and off again but still same problem. no rush to fix this but this is the only cheat i trust you do good work man so good luck keeping this thing working, cheers, let me know if you find another fix, goodnight.
> 
> maybe it is enabled in config you use

its disabled in default config which is what ive been testing, someone said to go back to 1.8 so ill try that

**Comment by HackingRats** [comment]
> I was using 1.8 and so far it's worked. Idisabled nade helper in the game rat poision menu.

which 1.8 are you usign?

**Comment by HackingRats** [comment]
> > I was using 1.8 and so far it's worked. Idisabled nade helper in the game rat poision menu.
> 
> which 1.8 are you usign?

latest 1.8 wont even load menu in main menu for csgo, trhows that error as soon as game starts

**Comment by ZeroKrazy** [comment]
I'm using the https://github.com/RatPoison-dev/RatPoison/tree/we-do-a-little one.

**Comment by HackingRats** [comment]
> I'm using the https://github.com/RatPoison-dev/RatPoison/tree/we-do-a-little one.

im trying it right now if it works your a fucking rat god man, i wonder why its called "we do a little" lol

**Comment by HackingRats** [comment]
> I'm using the https://github.com/RatPoison-dev/RatPoison/tree/we-do-a-little one.

It worked thanks man, bit of a differnt gui but atleast it works, gg all the way man appreciate it

**Comment by ZeroKrazy** [comment]
No worries, glad it helped!

**Comment by ZeroKrazy** [comment]
"New Update" so I started up ratpoision today and after a few minutes of playing, I got the error in CMD and I could no longer upen my menu. I didn't have grenade helper enabled.


10.199707
0.12731934
0.109680176
0.09082031
0.074645996
0.055847168
0.041809082
0.026428223
0.008361816
5.1827393
0.1638794
0.14953613
0.13171387
0.116760254
0.099731445
0.084228516
0.06530762
0.047424316
0.030151367
0.012451172
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke$lambda-1(NadeTracer.kt:59)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1682)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke(NadeTracer.kt:54)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke(NadeTracer.kt:27)
        at rat.poison.overlay.App.render(App.kt:269)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$initApp$1.invokeSuspend(RatPoison.kt:210)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at rat.poison.RatPoison.initApp(RatPoison.kt:207)
        at rat.poison.RatPoison.main(RatPoison.kt:196)
        at rat.poison.RatPoison.main(RatPoison.kt)

**Comment by ZeroKrazy** [comment]
This is my recent try and issue with the menu closing.
"
Menu Key: Insert
10.190002
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke$lambda-1(NadeTracer.kt:59)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1682)
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke(NadeTracer.kt:54)
        at rat.poison.scripts.visuals.NadeTracerKt$nadeTracer$1.invoke(NadeTracer.kt:27)
        at rat.poison.overlay.App.render(App.kt:269)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$initApp$1.invokeSuspend(RatPoison.kt:210)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at rat.poison.RatPoison.initApp(RatPoison.kt:207)
        at rat.poison.RatPoison.main(RatPoison.kt:196)
        at rat.poison.RatPoison.main(RatPoison.kt)
Type help for options

10.193939
6.9288025
9.363464
10.194275
7.4767456
"

**Comment by hennessy1337** [comment]
config for RatPoison-we-do-a-little?

**Comment by ZeroKrazy** [comment]
I can't tell if you're asking for my config or asking if I have a config FOR  we do a little. 
I made a config in we do a little.
I made it with aimbot, skeleton, chams, rcs.
