### ISSUE TITLE
[QUESTION] Menu didn't start

### ISSUE THREAD

**Issue by whitethekiller** [RatPoison-dev/RatPoison#827]
I dont know what my settings changed or updates, but suddenly my ratpoison cant run.
im using ratpoison 1.7.

the command prompt showed this :

java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.StrafeHelperKt$strafeHelper$$inlined$every$1.run(Every.kt:31)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.StrafeHelperKt$strafeHelper$$inlined$every$1.run(Every.kt:31)

Pls help
![Capture](https://user-images.githubusercontent.com/87475990/125775677-c8f6fbdb-25c8-4fba-9028-904ac9d9c971.PNG)

**Comment by SPRAVEDLIVO** [comment]
[!caption](https://media.discordapp.net/attachments/752517512733655103/787672299641634828/image0.gif)

**Comment by SPRAVEDLIVO** [comment]
#818
