### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by braka490** [RatPoison-dev/RatPoison#836]
i am facing error when i start the game 
log are as follow 
Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Waiting for App
Initializing overlay
Overlay initialized
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalStateException: Failed to resolve offset
            at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
            at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
            at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
            at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
            at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
            at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
            at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
            at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:26)
            at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
            at rat.poison.overlay.App.render(App.kt:174)
            at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
            at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
            at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
            at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:169)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
            at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
            java.lang.IllegalStateException: Failed to resolve offset

**Comment by sotakoira** [comment]
download newest version from github

**Comment by braka490** [comment]
yes it is lastest one. Lastest release

**Comment by sotakoira** [comment]
nope, latest release has that offset fixed
