### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by morequin** [RatPoison-dev/RatPoison#847]
Hi i have java jdk 17 and i got this error when i went into a match i had skeletons, rcs, and aim on.
Loading settings...
Settings loaded
Waiting for "Counter-Strike: Global Offensive" process...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Game found. Launching.
Waiting for App
Initializing overlay
Overlay initialized
Exception in thread "DefaultDispatcher-worker-1" java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:648)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt:28)
        at rat.poison.scripts.visuals.HeadLevelHelperKt$headLevelHelper$1.invoke(HeadLevelHelper.kt)
        at rat.poison.overlay.App.render(App.kt:185)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:190)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.RCSKt$rcs$$inlined$every$1.run(Every.kt:50)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.run(Every.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.run(Every.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.run(Every.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException: Failed to resolve offset
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:44)
        at rat.poison.game.offsets.Offset$address$2.invoke(Offset.kt:12)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at rat.poison.game.offsets.Offset.getAddress(Offset.kt)
        at rat.poison.game.offsets.Offset.getValue(Offset.kt:51)
        at rat.poison.game.offsets.EngineOffsets.getDwViewAngles(EngineOffsets.kt)
        at rat.poison.game.ClientStateKt.angle(ClientState.kt:11)
        at rat.poison.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.run(Every.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:832)
Thank you for reading!

**Comment by sotakoira** [comment]
update your cheat, if server timeouts blame whatever hosts shared esp
