### ISSUE TITLE
[BUG] Installer failed

### ISSUE THREAD

**Issue by JoshyJoshyVR** [RatPoison-dev/RatPoison#865]
**Describe the bug**

Some exception occurred, please report in discord (https://dimden.dev/ratpoisonowns):
----CUT HERE----
Installer settings:
{
    "build_folder": "build/",
    "bypass_download": false,
    "download_missing_files": true,
    "force_cheat_compile": false,
    "force_cheat_update": false,
    "force_install_jdk": false,
    "github_repo": "TheRatCode/RatPoison",
    "jdk_installation_path": "C:\\Users\\my name but removed for privacy\\AppData\\Roaming",
    "jdk_link_x64": "https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_windows-x64_bin.zip",
    "jdk_link_x86": "https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x86-32_windows_hotspot_14.0.2_12.zip",
    "jdk_zip_name": "JDK.zip",
    "settings_directory": "settings/",
    "show_last_X_commits": 5,
    "skip_jdk_checks": false,
    "update_type": "call_installer"
}

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/TheRatCode/RatPoison/git/trees/master?recursive=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "installer.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "main.py", line 82, in <module>
  File "compile_tools.py", line 19, in compile
  File "repository.py", line 83, in compare_tree
  File "repository.py", line 62, in get_tree
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/TheRatCode/RatPoison/git/trees/master?recursive=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))
Press any key to continue . . .

**To Reproduce**
Add steps on how to reproduce this issue/bug, if you don't this issue will be closed and won't be looked into.
Run instller.bat

**Pictures/Videos**
If applicable, add screenshots or link a video to help explain your problem.

I have windows 11. Could it be that my csgo is on an external drive?

**Comment by JoshyJoshyVR** [comment]
Nevermind, I think It might be that CSGO is not running

**Comment by SPRAVEDLIVO** [comment]
you exceeded ratelimit on github api
(might get fixed at some point)

**Comment by JoshyJoshyVR** [comment]
Now it works, might be my school wifi blocking the API
